version: '2'

services:
  test:
    build: ./ 
    command: npm run test
    links:
      - database
      - cache
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - database
      - cache
     
  database:
    image: mongo

  cache:
    image: redis

  